### ISSUE TITLE
Anpassung Ortsuche

### ISSUE THREAD

**Issue by svenkaemper** [wisydb/wisy#11]
"Die Ortssuche / Datums-Suche verwirrt regelmäßig, wenn das Listenergebnis eine Durchführung zufällig mit einem anderen Ort oben in der Liste zeigt. Pro Zeile genau den gesuchten Ort / Datum in den Durchführungen suchen und anzeigen. Und ggf. trotzdem die Zeile darunter (XX weitere Orte/Termine)"

**Comment by svenkaemper** [comment]
@meyway @debagel Hier sollte man vor dem Start die exakten Anforderungen genau klären und die Auswirkungen auf die gesamte Suche (Performance, Filter) prüfen… könnte eine umfangreichere Geschichte werden. 

Zudem wird "X weitere" ja bereits bei den Terminen mit angezeigt, in der Spalte "Ort" würde ich da weitere Zusatzinfos eher vermeiden wollen.

**Comment by debagel** [comment]
Aktueller Wunsch ist das die Anzeige der Kursliste überarbeitet wird: Bei gefilterter Kursliste soll für jeden Kurs soweit möglich eine der zu den gesetzten Filtern passende Durchführung gefunden und deren Daten für Termin, Dauer, Art, Preis, Ort angezeigt werden. Nicht wie bisher einfach die Daten der ersten DF. Theoretisch sollte es ja immer eine DF geben die auf alle relevanten gesetzten Filter passt.

**Comment by debagel** [comment]
@wisydb Hier gibt es aus meiner Sicht für die Ortsfilterung zwei technisch sehr unterschiedliche Fälle. Relativ einfach ist der Fall, dass nur nach **bei:** gefiltert wird ohne **km:** (Umkreis). Dann sollte es ohne weitere Datenbankabfragen möglich sein die Durchführungsdaten anzuzeigen die zum gefilterten Ort passen.

Wenn aber auch nach Umkreis gesucht wird und für den gefilterten Ort direkt keine DF vorliegt (also nur DF im Umkreis, keine im Ort selbst) ist es nicht mehr so einfach zu entscheiden welche die Naheliegendste ist. Dazu bräuchten wir Koordinaten auf Kursebene analog zu x_kurse_latlng. Den Fall lasse ich also erstmal unberücksichtigt.

**Comment by debagel** [comment]
@wisydb Im aktuellen DEV-Branch ist das jetzt testbar. Wenn nach Ort gefiltert wurde wird nach einer Durchführung gesucht die im gefilterten Ort stattfindet und diese verwendet statt der ersten DF.

Wenn nach Datum gefiltert wird wird nach einer Durchführung gesucht die am oder nach dem gefilterten Datum stattfindet und diese verwendet statt der ersten DF.

Wenn nach Ort UND Datum gefiltert wird wird trotzdem nur versucht den Ort anzupassen.

**Comment by debagel** [comment]
@wisydb Bitte noch mal testen. Die Anzeige der zum gesuchten Ort passenden Durchführung sollte jetzt besser klappen.

**Comment by wisydb** [comment]
Stichwort 1, Stichwort 2, Stichwort n, Ort funktioniert, wie erwartet => die passende DF wird angezeigt.

Umkreis-Suche:
Genau - sowohl mit km als auch ohne - unberücksichtigt lassen.

_"Wenn nach Datum gefiltert wird wird nach einer Durchführung gesucht die am oder nach dem gefilterten Datum stattfindet und diese verwendet statt der ersten DF."_
Funktioniert nicht mehr (auch ohne Ort nicht). Funktionierte aber schon mal.

_"Theoretisch sollte es ja immer eine DF geben die auf alle relevanten gesetzten Filter passt."_
Leider nicht, denke ich.

_"Wenn nach Ort UND Datum gefiltert wird wird trotzdem nur versucht den Ort anzupassen."_
Da es die anderen Kriterien noch gibt = suboptimal. Gleichzeitig kann man natürlich nicht "magisch" die am passendste bestimmen, wenn mind. 2 Kriterien gefiltert werden und diese sich auf 2 unterschiedlich verteilen.

Folglich wäre informations-transparent für mehrere Kriterien (s. 19.10.18 oben) nur: 

Szenario:
Kurs hat 3 DF:
DF1: Datum: Jan | Ort: Hamburg
DF2: Datum: Feb | Ort: Lübeck
DF3: Datum: Mrz | Ort: Bremen


Filter: 
Datum: Jan, Ort Lübeck 

Folgt im Ergebnis in der (selben) Kurszeile für die DF-Spalten Termin und Ort:
<em>Jan</em> | Hamburg
Feb | <em>Lübeck</em>
1 weiterer... |

**Comment by debagel** [comment]
@wisydb Bitte noch mal testen. Es sollten jetzt für "Termin" und "Ort" zwei Werte untereinander ausgeben werden wenn nötig, wie in deinem Beispiel oben dargelegt.

**Comment by wisydb** [comment]
Mit der neuen Funktion funktioniert alles, wie hier beschrieben! Danke.

Kleiner Bug mit dem Link "1 weiterer..." etc. => der ist leer (nach /k kommt keine ID), wenn Du z.B. folgende Anfrage, die Live noch funktioniert, mal in der Sandbox1 testet:
sh.kursportal.info/search?qs=P%E4dagogik+f%FCr+Ganztagsschulen%2C+Pr%E4senzunterricht%2C+Datum%3A27.08.2021&q=P%E4dagogik+f%FCr+Ganztagsschulen%2C+Pr%E4senzunterricht%2C+datum%3A18.02.2022&qf=
