### ISSUE TITLE
Cookie-Banner

### ISSUE THREAD

**Issue by svenkaemper** [wisydb/wisy#17]
Der HTML-Code des Cookie-Banners sollte im Hinblick auf seine Semantik überarbeitet werden; bitte valides HTML5-Markup (strong statt b, Headlines und p statt br, keine verschachtelten b-Tags).

Zudem sollte der Banner den Inhalt der Seite nicht überlagern – in RLP wird beispielsweise die Navigation komplett vom Banner verdeckt. 

Zu prüfen wäre auch, ob man nicht auch eine Lösung wie https://cookieconsent.insites.com verwenden kann.

**Comment by svenkaemper** [comment]
Für das Weiterbildungsportal RLP angepasster Beispiel-Code von o.g. Anbieter:

```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#eeeeee"
    },
    "button": {
      "background": "#a42244"
    }
  },
  "position": "bottom-right",
  "content": {
    "message": "Wir verwenden Cookies, um Ihnen eine Merkliste sowie eine Seitenübersetzung anzubieten und um Kursanbietern Pflege ihrer Kurse zu ermöglichen. Indem Sie unsere Webseite nutzen, erklären Sie sich mit der Verwendung der Cookies einverstanden. Weitere Details finden Sie in unserer Datenschutzerklärung.",
    "dismiss": "Verstanden!",
    "link": "Mehr erfahren",
    "href": "https://weiterbildungsportal.rlp.de/g12631"
  }
})});
</script>
```

Diese Konfiguration blendet einen "schwebenden Hinweis" in der unteren rechten Ecke des Portals ein, bis der Nutzer diesen entfernt. Alternative Positionierungen sind über das Konfigurationstool möglich.

**Comment by svenkaemper** [comment]
Genaue Anforderungen an den Cookie-Banner sind vorab noch zu klären:

- Anzahl, Art und Konfiguration der eingesetzten Cookies (global vs. portalspezifisch)?
- Opt-in vs. Opt-out?
- Zustimmung je Cookie oder global?
- juristische Vorgaben und Prüfung (inhaltlich/funktional)?

(Zu überlegen wäre zudem, ob man im Zuge der DSGVO die Cookies nicht auch einfach reduzieren sollte? Wenn ich es richtig sehe, werden beispielsweise auf https://hamburg.kursportal.info acht (!) Cookies gesetzt…? Sind die wirklich alle erforderlich?)

**Comment by svenkaemper** [comment]
Könnte ebenfalls hilfreich sein, falls o.g. Methode nicht ausreicht: https://github.com/snipsco/yett ("A small webpage library to control the execution of (third party) scripts like analytics")

**Comment by debagel** [comment]
Ich fasse noch mal zusammen was @svenkaemper schon zusammengetragen hat und was mir noch dazu einfällt mit der Bitte um Freigabe an @meyway so das ich die Umsetzung angehen kann:

1. Wir bauen auf einer Open Source Lösung wie https://cookieconsent.insites.com auf. Diese muss lokal einbaubar sein (also nicht von extern geladen werden) und gut konfigurierbar sein.

2. Falls notwendig ergänzen wir das um eine weitere Open Source Lösung wie https://github.com/snipsco/yett um (externe) Skripte zu blocken solange die Zustimmung fehlt.

3. Einige Grundlegende Einstellungen können auf Portal-Ebene vorgenommen werden:

A. Position des Cookies: Oben oder unten schwebend. Oben "schiebend". In Ecke schwebend (links, rechts, oben, unten)

B. Art des Cookie-Banners: Info, Opt-Out, Opt-In. Wird nur informiert und keine Zustimmung eingefordert oder wird die Zustimmung vorausgesetzt mit der Option diese zu verweigern oder wird die Zustimmung explizit erst eingeholt? Siehe https://cookieconsent.insites.com/documentation/compliance/

Manche Websites unterscheiden auch zwischen "funktionalen Cookies" (die für den Betrieb der Website notwendig sind) und "Statistik Cookies" (Tracking usw.) und erlauben dem Nutzer letztere abzustellen. Das verkompliziert die Umsetzung natürlich etwas. Ist das notwendig aus juristischer Sicht, @meyway ?

C. Link zur Datenschutzerklärung des Portals

D. Welche Cookies bei welcher Zustimmung erlaubt / geblockt sind. Falls wir in B. zwischen Cookie-Gruppen ("funktional" vs. "statistisch") unterscheiden muss hier auch die Zuordnung der Cookies zu den Gruppen stattfinden.

**Comment by debagel** [comment]
Das ganze ist jetzt testbar auf <http://testcookie.kursportal.info>. Die einmal getroffenen Cookie-Einstellungen (Ablehnen oder Akzeptieren) können jederzeit auf der Seite "Datenschutzhinweise" durch Klick auf "Cookie-Einstellungen" angepasst werden.

Wir haben uns für "Opt-Out" entschieden und alle Logik entsprechend umgesetzt. Der Nutzer hat also die Möglichkeit pauschal Cookies zu Akzeptieren oder sie Abzulehnen. Wenn er ablehnt werden sofort alle gesetzten Cookies gelöscht und keine neuen mehr gesetzt außer dem Cookie das seine Cookie-Einstellungen speichert.

Dabei habe ich bisher Google Analytics, Piwik und die FAV-Funktion berücksichtigt.

Weitere Cookies können in den Portaleinstellungen namentlich aufgelistet werden. Diese werden dann auch gelöscht. Das neu-setzen dieser Cookies müsste man dann aber irgendwie anderweitig verhindern.

Einen Link / Button zum erneuten Anzeigen des Cookie-Einstellungen-Popups kann man an beliebiger Stelle im Portal unterbringen, es benötigt nur die ID #wisy_cookieconsent_settings.

Darüber hinaus gibt es folgende Einstellungen je Portal, fast alle mit Default-Werten falls sie nicht gesetzt werden:

cookiebanner = 1
cookiebanner.cookiegueltigkeit = 365
cookiebanner.datenschutz.text = Mehr erfahren...
cookiebanner.datenschutz.link = /g12731

cookiebanner.cookies.optout = namen, der, zulöschenden, cookies
cookiebanner.fav.optouthinweis = Hinweis wenn bei deaktivierten Cookies die FAV-Funktion genutzt wird

cookiebanner.position = bottom-right
cookiebanner.hinweis.text = Lorem ipsum
cookiebanner.hinweis.hintergrundfarbe = #000
cookiebanner.hinweis.textfarbe = #FFF
cookiebanner.hinweis.linkfarbe = #00F
cookiebanner.erlauben.text = Erlauben
cookiebanner.erlauben.buttonfarbe = #0F0
cookiebanner.erlauben.buttontextfarbe = #FFF
cookiebanner.ablehnen.text = Ablehnen
cookiebanner.ablehnen.buttonfarbe = #F00
cookiebanner.ablehnen.buttontextfarbe = #FFF

**Comment by debagel** [comment]
@wisydb 
Die Dokumentation des Cookiebanners ist jetzt im WIKI bei den Portaleinstellungen und auf der neuen Seite http://b2b.kursportal.info/index.php?title=Cookiebanner online.

**Comment by wisydb** [comment]
🥇  :-)

Letzte Info bzgl. Default-Blockieren aller Cookies war wie weitergeleitet: erst mal keine Veränderung notwendig. Habe noch mal nachgefragt. Noch keine erneute Aussage vorliegend. GGf. eröffne ich diesen Issue wieder oder mache einen neuen auf, wenn nötig.
