### ISSUE TITLE
Landingpages für Abschlüsse

### ISSUE THREAD

**Issue by svenkaemper** [wisydb/wisy#18]
- [x] Übersichtsseite mit Auflistung aller Abschlussarten
- [ ] Einträge dieser Auflistung rufen keine Suche auf, sondern verlinken auf zum Teil bereits bestehende Glossarseiten, die aktuell über ein Info-Icon erreichbar sind
- [x] auf diesen Glossarseiten erfolgt direkt die Auflistung der Kursangebote inkl. Filterleiste
-  [x] Verwendung „lesbarer“ URLs wie beispielsweise https://[portal-URL]/abschluesse und https://[portal-URL]/abschluesse/techniker_in-mechatronik

**Comment by debagel** [comment]
> auf diesen Glossarseiten erfolgt direkt die Auflistung der Kursangebote inkl. Filterleiste

D.h. auf diesen Glossarseiten steht oben erstmal der eingegebene normale Inhalt der Glossarseite und darunter erscheint dann eine Kursliste (Suchergebnis der Suche nach dem jeweiligen Abschluß). 

Meine erste Idee wie das technisch gut machbar ist wäre jetzt das man eine Art "shortcode" / WIKI-Syntax oder so an beliebiger Stelle im Glossartext eingibt der dann von PHP bei der Ausgabe durch die entsprechende Kursliste ersetzt wird. Also zb. "[kursliste suche="blablabla"]".
@wisydb hältst du das für sinnvoll so? Oder anders?

**Comment by wisydb** [comment]
Dieses mit Vanit-URL erfüllt ja im Grunde Punkt 1 ("Übersichtsseite mit...") von ganz oben https://sh.kursportal.info/g1005, nur dass das Info-i über den Abschluss-Text-Link verlinkt ist oder so. Punkt 3 ("Auf diesen Glossarseiten erfolgt direkt die Auflistung...") entspricht dann ungefähr der aktuellen Funktion der Text-Links nur zu Suche mit Filter usw. Und am wichtigsten Punkt 4, autom. Generierung der Abschluss-URLs mit Übermittlung an Google(?) via sitemap.xml.

Ich finde gut, dass Du einen eigenen Landingpage-Renderer angelegt hast: Es ist eigenständiger bzw. an der Stelle wo "edit", "search" usw. abgefangen wird ist auch nur eine Umleitung zu anderen Renderern...

Inhalt Glossarseite: ich denke, so wie Du geschrieben hast. Schau Dir hier unter Abschlüsse mal die konkreten Abschlüsse an:
https://hamburg.kursportal.info/

I.d.T. sind das manuell angelegt, wie https://hamburg.kursportal.info/g233 . Jedoch wird der Baum hier über IDs generiert und funktioniert nur mit (Sach)Stichwörtern.

"[kursliste suche="blablabla"]":
Ja, könnte man so machen, die Funktion wäre so oder so wohl sinnvoll. Dann wären IDs (zusätzlich? -> Mehrarbeit) evtl. Komma-separiert, geschickter, weil man so eben die Glossarseiten nicht anpassen muss, wenn man ein SW ändert?

-- Schnitt -- 

Andererseits:
Wenn aus den SW, die die Abschlüsse ausmachen, autom. dazu führen, dass solche URLs generiert werden (https://[portal-URL]/abschluesse und https://[portal-URL]/abschluesse/techniker_in-mechatronik) - ähnlich den Orts-Landingpages - wozu braucht man dann noch den Shortcode? Die Suchergebnisse/Suche wird ja automatisch für diese URL generiert. Müsste der Shortcode wenn dann nicht dazu dienen, dass sich eine Glossarseite automatisch dieser Suche "zuordnet" nämlich darüber erscheint? Und nur wenn kein Glossareintrag zu einer Suche existiert erscheint darüber nichts? Vielleicht meintest Du das auch, dann habe ich es vll. misinterpretiert.

Sollen wir dazu nochmal telefonieren?
