### ISSUE TITLE
Landingpages für Orte

### ISSUE THREAD

**Issue by svenkaemper** [wisydb/wisy#19]
Landingpages für optischen und maschinenlesbaren Orts-Bezug Hamburg + Stadtteile (Beispiel: hamburg-aktiv.info/orte/Hamburg-Heimfeld). Für diese Schreibweise müsste man das Ortsfeld mit dem Stadtteilfeld kombinieren.

**Comment by wisydb** [comment]
Ja. S. Kommentar Landingpages für Thema + Orte. Also beides Ort + Stadtteil, aber Stadtteil abschaltbar (default: aus).
