### ISSUE TITLE
Landingpages für Thema + Ort

### ISSUE THREAD

**Issue by svenkaemper** [wisydb/wisy#20]
- [x] URL-Generierung für Stichwort-Ort-Kombinationen, sofern Kurse vorhanden (z. B. http://[portalurl]/spanisch-in-hamburg)
- [x] Stichwörter sind über Portaleinstellungen redaktionell pflegbar
- [x] Übermittlung der URLs an Google via Sitemap
- [x] Anpassungen Seitentitel („Spanisch in Hamburg“)
- [x] Anpassungen Überschrift der Kursliste („36 Angebote zum Suchauftrag ‚Spanisch‘ in Hamburg“)

**Comment by svenkaemper** [comment]
@meyway Ich nehme an, speziell für Hamburg sollen auch hier bei URL und Seitentitel/Überschriften die Stadtteile berücksichtigt werden ("Spanisch in Hamburg-Heimfeld")…?

**Comment by wisydb** [comment]
Das hängt leider sehr vom Thema ab: bei exotischeren Kursthemen, also selteneren Angeboten, sowie bei Beratungsangeboten ist eine stadtweite Erwähnung sinnvoll. Bei freizeitlastigen Themen, schulischen Angeboten und häufigen Angeboten wäre eine stadtteil-bezogene ggf. bezirksbezogene Landingpage sinnvoll. Bezirke gibt es aber z.Z. nicht als geographische Eben, also z.Z. auszuklammern. Darum wäre die Maximallösung vll. sinnvoll, man müsste ja nur das Stadtteilfeld anhängen und dann eine Portaleinstellung zu schaffen, die das Hinzufügen des Stadtteils pro Portal ausstellt (für Flächenländer).

**Comment by wisydb** [comment]
Anpassungen Seitentitel („Spanisch in Hamburg“) <- Dies bezieht sich auf den Titel der Landingpage, korrekt?

**Comment by svenkaemper** [comment]
Gemeint ist sowohl der Seitentitel (also das, was oben sichtbar für den Nutzer als Headline steht), als auch natürlich der <title>-Tag.

**Comment by wisydb** [comment]
Alles klar. Ich meinte nur, es bezieht sich auf die Landingpages... Denn für die anderen Seiten passe ich es gerade an, also bei Anbieterseiten steht in Zukunft eh nicht mehr "Sprachanbieter XYZ" sonder "Sprachanbieter XYZ in Mainz" usw..

**Comment by svenkaemper** [comment]
@wisydb @debagel Nochmal zu den Stadtteilen: Ich würde das oben beschriebene Verhalten aber nicht für einzelne Themen konfigurieren, sondern sehe das eher als eine "globale" Einstellung für alle Themen. Wenn die Einstellung gesetzt ist, werden allen vorhanden Themen der Ort plus Stadtteil angehängt ("Spanisch in Hamburg-Heimfeld"), wenn nicht, dann nicht. Also nicht: Bei Thema A den Stadtteil anhängen, bei Thema B aber nicht…

Zudem sollte es m. E. auch immer eine übergeordnete Seite geben ("Spanisch in Hamburg").

**Comment by meyway** [comment]
Genau, global pro Portal. Alles andere würde programmiertechnisch und in der Pflege z.Z. zu sehr ausarten...

**Comment by debagel** [comment]
@wisydb Ich überlege gerade wie ich alle Landingpages in die bestehende Sitemap einbinde. Ich tendiere dazu weitere Sitemaps anzulegen so das wir dann neben der bestehenden Sitemap noch zb. sitemap-orte.xml, sitemap-themen.xml, sitemap-abschluesse.xml haben. 
Dann können wir in sitemap.xml einen Sitemap index ausgeben der auf die obigen Landingpage Sitemaps und die (dann in zb. sitemap-kurseundanbieter.xml umzubenennende) bestehende Sitemap verweist.
Wir könnten auch die bestehende Sitemap noch weiter aufspalten in sitemap-kurse.xml und sitemap-anbieter.xml.
Was meinst du?

**Comment by debagel** [comment]
ps: Das aufsplitten wird zb. hier empfohlen für große Sitemaps: https://support.google.com/webmasters/answer/75712?hl=en

**Comment by debagel** [comment]
Hab das jetzt in core51 auch in der robots.txt hinzugefügt
