### ISSUE TITLE
Suche nach Namensverweisungen mit 1:n - Abbildung (statt nur 1:1)

### ISSUE THREAD

**Issue by wisydb** [wisydb/wisy#36]
Oder Suche bei Namensverweisungen mit mehreren Verweisen statt "tag_not_found"-error.

**Comment by wisydb** [comment]
Wenn ein Synonym, Synonym für mehrere SW ist ergibt die Suche null Ergebnisse, obwohl es bei lediglich einer Zuordnung Ergäbnisse gäbe. Ursache hier, Z. 762:
https://github.com/wisydb/wisy/blob/master/core51/wisy-search-class.inc.php

Es wäre sinnvoll eine Suche nach allen zugeordneten Begriffen durchzuführen (und dabei idealerweise böse Schleifen auszuschließen) und diese Suchen zu einer zusammenzuführen.

**Comment by debagel** [comment]
@wisydb Sieht aus als wäre das abgeschlossen. Oder gibt es da noch was zu tun?

**Comment by wisydb** [comment]
Ist erledigt, funktioniert wieder.
