### ISSUE TITLE
Seite "Suchvorschläge" überarbeiten

### ISSUE THREAD

**Issue by svenkaemper** [wisydb/wisy#4]
Die Vorschlagsliste am Eingabefeld der Kurssuche auf http://weiterbildungsportal.rlp.de zeigt bei einer Eingabe ganz unten als letzten Eintrag „Alle Suchvorschläge anzeigen“ an und bringt den Nutzer bei Klick auf eine Seite mit sämtlichen Vorschlägen.

Für die Kurssuche funktioniert das auch wunderbar, im Anbieterverzeichnis leider nicht, da WISY für die Seite mit den Suchvorschlägen scheinbar keine weitere Eingrenzung oder "Vorfilterung" zulässt. Man bekommt daher im Anbieterverzeichnis immer sämtliche Suchvorschläge angezeigt – idealerweise sollten hier nur Vorschläge vom Typ "Träger" (=Anbieter) erscheinen.

=> Überarbeitung der Seite "Suchvorschläge" unter Berücksichtigung der o.g. Anforderungen.

**Comment by debagel** [comment]
@wisydb Im aktuellen DEV-Branch ist das jetzt testbar. Wenn in der Anbieterliste gesucht und auf "Alle Suchvorschläge anzeigen" geklickt wird wird auf der "Suchvorschläge zum Stichwort ..." Seite jetzt nach Anbietern gefiltert.

**Comment by debagel** [comment]
@wisydb Nicht-verlinkte Einträge sollten jetzt nicht mehr in der Liste vorkommen. Bitte noch mal testen ob noch Probleme vorhanden sind.

**Comment by wisydb** [comment]
Es funktioniert / ist jeweils sinnvoll aufrufbar, Namensverweisungen und Markierungen sinnvoll.

Intern: Angebote-Vorschläge: "Träger"-Vorschläge können/müssen hier nun entfernt werden. Nicht Teil dieser Aufgabe.
