### ISSUE TITLE
Suche geht nicht! search?q=

### ISSUE THREAD

**Issue by regiomac** [wisydb/wisy#72]
Ich habe eine neue Installation aufgesetzt. Es wurden Daten in die DB eingegeben, aber wenn ich suche bekomme ich eine 404 Fehlermeldung. Jemand eine Ahnung?
The requested URL /search was not found on this server.

**Comment by wisydb** [comment]
Wenn schon /search nicht gefunden wird (oder liefert die Suche nur keine Ergebnisse?), vermute ich - ohne weiteren Kontext - dass .htaccess und/oder index.php nicht im Hauptverzeichnis liegen oder die Kerneinstellung nicht vorgenommen wurde (die Seiten wie /search, /edit usw.) näher definiert/abfängt.

**Comment by wisydb** [comment]
**Systemvoraussetzungen**

- Apache mit mod_rewrite(!)
- PHP, mind. 5.1.2, s. admin/classes.inc.php, register_globals ist nicht meht notwendig halbwegs aktuelles MySQL
- für Import/Export/Synchronisierung: PDO Driver for SQLite

**Installation**
- den Quelltext in das Rootverzeichnis einer Domain kopieren, so dass z.B. das Verzeichnis admin/ unter http://www.example.com/admin/ erreichbar ist (zum Testen können auch einfach http://localhost oder http://localhost:port verwenden; die Installation in ein Unterverzeichnis wird nicht empfohlen; vergessen Sie beim Kopieren bitte nicht die versteckte Datei .htaccess) 

- eine neue MySQL-Datenbank mit collation "latin1_german1_ci" erstellen. Textvergleiche, z.B. für Suchergebnis-Ordnung verhalten sich wie folgt - latin1_german1_ci: Ä = A, ß = s; latin1_german2_ci: Ä = AE, ß = ss. Die Tabellen-Collations werden aber durch die zu importierende db.sql bestimmt.

- Dort dann die Datei admin/config/db.sql importieren ("Zeichencodierung der Datei" = ISO8859-15), was die notwendigen Tabellen erzeugt. 

- admin/config/config.inc.php-defaults nach admin/config/config.inc.php kopieren und dort jeweils die Zugangsdaten zur MySQL-Datenbank eintragen, die Einstellungen zur Synchronisierung (Multi-Master-Replikation) können erst einmal ignoriert werden. Außerdem hier die Domains anpassen u.a. für den Secure-Login/Redirect des Adminbereichs.

Das war's - theoretisch.

- Unter http://www.example.com/admin/ finden Sie das CMS bzw. das Redaktionssystem. Dort können Sie sich initial mit dem Benutzer root ohne Passwort anmelden. Der erste Schritt sollte dann sein, dem Benutzer unter "Etc. / Benutzer" ein Passwort zu verpassen

- unter http://www.example.com finden Sie nun ein Standardportal; hierfür ist es allerdings notwendig, dass mind. ein Portal im Redaktionssystem für die verwendete Domain angelegt wird, dieses erste Portal sollte auch die Wildcard erhalten, also Domaineinstellung also z.B. www.example.com, * wählen

- Es muss ein Kern im Portal definiert sein, entspr. dem Kernverzeichnisnamen, z.B. `core = 51` Um alle freigegebenen Kurse der DB anzuzeigen: keinen Portalfilter in den Portaleinstellungen definieren -> s. Portaleinstellungen in "Nach der Installation".

- Für portalspezifische und sonstige Dateien legen Sie am besten ein Verzeichnis http://www.example.com/files/ an, evtl. mit Unterverzeichnissen für jedes Portal.

**Nach der Installation**

Hier ein paar weitere Konfigurationsoptionen in loser Reihenfolge, ohne Anspruch auf Vollständigkeit:

- Der Suchindex für die Portale muss durch regelmäßigen Aufruf des Skripts http://www.example.com/sync auf den aktuellen Stand gehalten werden!

- **D.h. nach dem Anlegen von ersten Beispiel-Datensätzen (Angeboten/Anbietern) tauchen diese noch nicht in der Suche auf. http://www.example.com/sync muss mind. 1 x aufgerufen werden und zwar mit Api-Key des Portals und der Option kurseSlow bzw. kurseFast => z.B.: http://www.example.com/sync?apikey=meinapikey&kurseSlow** - in diesem Fall ist also in den Portaleinstellungen des jeweiligen Portals einzutragen: `apikey = meinapikey`

- Das System liefert bei Bedarf automatisch die Dateien http://www.example.com/robots.txt und http://www.example.com/sitemap.xml.gz aus; falls die Test-Installation auf einem öffentlichem Server läuft, Suchmaschinen diese aber _nicht_ indizieren sollen, ist im www-root-Verzeichnis eine robots.txt sinnvoll:
```
 User-agent: *
 Disallow: /
```
Ferner wäre die automatische Übermittlung der .../sitemap.xml an Google zu verhindern.

- AddCharset etc. auf ISO-8859-1, mindestens aber Browseransicht entsprechend einstellen.

- Datenbankinhalte können per Synchronisation übertragen werden. Für jeden Neuinstallation ist eine eigene Installationsnummer erforderlich, die vom Urheber vergeben wird. Ohne diese Nummer handelt es sich um eine Insel-Installation ohne Synchronisationsmöglichkeiten.

- Weitere Portale können aufgeschaltet werden, indem weitere Domains einfach in dasselbe htdocs-Verzeichnis zeigen; dies ist besonders mit CatchAll-Subdomains praktisch, da dann Portale ohne weitere Serverkonfiguration komplett aus dem Redaktionssystem heraus erstellt werden können

- Klicken Sie oben auf den Reiter "etc. “ -> Editieren Sie die Benutzergruppen: http://.../admin/edit.php?table=user_grp -> Legen Sie evtl. eine Gruppe an: z.B. admingruppe, Admingruppe -> Stellen Sie in "Rechte" sicher, dass alles ausgewählt ist also: "*.*". 

- Wählen Sie oben auf den Reiter "etc. “ und wählen Sie "Benutzer" (http://www.example.com/admin/index.php?table=user) und zwar Oben auf "neu" klicken. -> Login-Name: wisyadmin -> Wählen Sie "Regel hinzufügen" (rechts unten), wählen Sie bei Tabelle, wie auch Felder "*" und "*". --> Hinzufügen --> Schließen -> Nun "Lesen", "Bearbeiten", "Neu", "Löschen" wählen . -> Stellen Sie in "Rechte" sicher, dass alles ausgewählt ist und fügen Sie den Nutzer zur Admingruppe hinzu. --> Übernehemen 

- Zum Testen loggen Sie sich am Besten aus ("X" rechts oben) und mit dem neuen User wieder ein.

- Nach erneutem Einloggen rufen Sie oben den Reiter "Portale" auf:
Klicken Sie oben auf "neu" und rufen füllen Sie das Formular aus. "Domains“ ist eine durch Komma getrennte Liste, z.B. „Stadtkursportal.de, Stadtkursportal.info“ -> Fügen Sie unter "Rechte" die "Admingruppe" hinzu.! --> übernehmen. 

- Hat alles geklappt, ist es hilfreich ein sql-Dump zu sichern. Nun können Sie unter „etc.“->“Benutzer“ den passwortlosen "root"-User löschen. 

- Portal bearbeiten: Oben rechts, hinter dem Link „Einstellungen“ können Sie die Portal-Editier-Fenster größer einstellen!

- Übernehmen Sie die Beispielinhalte für den Reiter "Einstellungen" und Layout ("HTML"+"CSS"- Feld) --> Übernehmen 

- Nun können Sie das Portal unter der eingestellten Domain im Browser aufrufen und es sollte ein realtiv blankes Portal erscheinen.

- Mit den Beispielinhalten am besten keine Kontaktmöglichkeiten im Portal nutzen.

- Im WISY-Root-Verzeichnis: .htaccess-Datei-Eintrag übernehmen:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^(.*)$ /index.php [L,QSA]
```
- Im WISY-Root-Verzeichnis einen Ordner "temp" anlegen und mit ausreichenden Schreibrechten ausstatten

- Sofern zutreffend und erlaubt: exportierten Themenbaum etc. von anderem Portal importieren via Menü etc. -> Import -> Mix-Datei

- unter http://www.example.com/api/ befindet sich eine REST-API

**Comment by regiomac** [comment]
Es lag an der Domainkonfiguration im Apache. Jetzt geht alles.
Danke!!
