### ISSUE TITLE
WISY: Lizenzwechsel

### ISSUE THREAD

**Issue by wisydb** [wisydb/wisy#75]
Bitte um Bestätigung aller "Contributors" (https://github.com/wisydb/wisy/graphs/contributors), dass alle Beiträge zu WISY (wie unter https://github.com/wisydb/wisy/ und https://github.com/wisydb/WISY-Mobilmodul abrufbar) unter "Mozilla Public Licence 2.0" stehen.

Lizenz-Text:
https://www.mozilla.org/en-US/MPL/

**Comment by wisydb** [comment]
J. Meyer: Bestätigung.

**Comment by meyway** [comment]
J. Meyer: Bestätigung.

**Comment by r10s** [comment]
Björn Petersen: Bestätigung

**Comment by debagel** [comment]
Daniel Bagel: Bestätigung

**Comment by svenkaemper** [comment]
Sven Kaemper: Bestätigung!
